package forms;

import forms.Form_stage_one;
import java.awt.List;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoundedRangeModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import pro.miner.classess.Corpus;
import pro.miner.classess.Global;
import pro.miner.classess.StartStemmer;
import static pro.miner.classess.StartStemmer.freqmodel;
import static pro.miner.classess.StartStemmer.wordsmodel;
import pro.miner.classess.TextMining;
import pro.miner.classess.TreeSelection;
import pro.miner.classess.WiktionarySearcher;
import pro.miner.classess.WordNetSearcher;
import pro.miner.classess.listWordSelection;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Devil Knight
 */
public class Form_text_mining extends javax.swing.JFrame {

    public static Boolean includeAgrovocDictionary = false;
    public static Set words = new HashSet<String>();

    /**
     * Creates new form TextMiningForm
     */
    public Form_text_mining() {
        initComponents();

        setVisible(true);
        jMenuItem1.setVisible(false);
        BoundedRangeModel model = jScrollPane3.getVerticalScrollBar().getModel();
        jScrollPane6.getVerticalScrollBar().setModel(model);
        //meaningPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contextstree = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        departmentField = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        folderPath = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        searchWord = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        addSource = new javax.swing.JButton();
        domain = new javax.swing.JButton();
        tastStatus = new javax.swing.JLabel();
        departmentName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        meaningArea = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        relatedWordsListWordNet = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        checkfile = new javax.swing.JCheckBox();
        checktok = new javax.swing.JCheckBox();
        checkstop = new javax.swing.JCheckBox();
        checkFreqCount = new javax.swing.JCheckBox();
        checktransform = new javax.swing.JCheckBox();
        checkStem = new javax.swing.JCheckBox();
        checkwordselect = new javax.swing.JCheckBox();
        selectedGlossaryFilePath = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listofwords = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        freqlist = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        select = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        relatedWordsListMerged = new javax.swing.JList();
        jScrollPane10 = new javax.swing.JScrollPane();
        relatedWordsListWiktionary = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        checkBoxIncludeAgrovocdDictionary = new javax.swing.JCheckBox();
        progressBarTextMining = new javax.swing.JProgressBar();
        jTextFieldGlossaryFile = new javax.swing.JTextField();
        select1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        fileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pro Miner - Text Mining");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(154, 180, 209));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 116, 193));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ProMine");

        contextstree.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Select a Directory");
        contextstree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        contextstree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                contextstreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(contextstree);

        departmentField.setEditable(false);
        departmentField.setColumns(20);
        departmentField.setRows(5);
        jScrollPane2.setViewportView(departmentField);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("File/Folder Path :");

        folderPath.setEditable(false);
        folderPath.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        folderPath.setPreferredSize(new java.awt.Dimension(6, 25));
        folderPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folderPathActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("Words");

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("Frequency");

        searchWord.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        searchWord.setText("Search");
        searchWord.setEnabled(false);
        searchWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchWordActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        reset.setText("Reset");
        reset.setEnabled(false);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        addSource.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        addSource.setText("Add Source Files");
        addSource.setEnabled(false);
        addSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSourceActionPerformed(evt);
            }
        });

        domain.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        domain.setText("Domain Expert");
        domain.setEnabled(false);
        domain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domainActionPerformed(evt);
            }
        });

        tastStatus.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        tastStatus.setText("Task Status");

        departmentName.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        departmentName.setText("Department Name");

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel7.setText("Meaning");

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 10)); // NOI18N
        jLabel8.setText("Related Words [Word Net]");

        meaningArea.setEditable(false);
        meaningArea.setColumns(20);
        meaningArea.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        meaningArea.setLineWrap(true);
        meaningArea.setRows(5);
        meaningArea.setWrapStyleWord(true);
        jScrollPane5.setViewportView(meaningArea);

        relatedWordsListWordNet.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        relatedWordsListWordNet.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane8.setViewportView(relatedWordsListWordNet);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        checkfile.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        checkfile.setText("Input File Read");
        checkfile.setEnabled(false);

        checktok.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        checktok.setText("Tokenization");
        checktok.setEnabled(false);

        checkstop.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        checkstop.setText("Stop Word Filteration");
        checkstop.setEnabled(false);

        checkFreqCount.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        checkFreqCount.setText("Frequency Counter");
        checkFreqCount.setEnabled(false);

        checktransform.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        checktransform.setText("Text Transformation");
        checktransform.setEnabled(false);

        checkStem.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        checkStem.setText("Stemming");
        checkStem.setEnabled(false);

        checkwordselect.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        checkwordselect.setText("Word Selection");
        checkwordselect.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkwordselect)
                    .addComponent(checkStem)
                    .addComponent(checkfile)
                    .addComponent(checktok)
                    .addComponent(checkstop)
                    .addComponent(checkFreqCount)
                    .addComponent(checktransform))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(checkfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checktok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkstop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkStem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkFreqCount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkwordselect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checktransform)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        selectedGlossaryFilePath.setEditable(false);
        selectedGlossaryFilePath.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel9.setText("Word to Define");

        listofwords.setModel(wordsmodel);
        listofwords.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listofwords.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listofwordsValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listofwords);

        freqlist.setModel(freqmodel);
        freqlist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                freqlistValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(freqlist);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro/miner/images/logo2.png"))); // NOI18N

        select.setText("Browse");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });

        relatedWordsListMerged.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        relatedWordsListMerged.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane9.setViewportView(relatedWordsListMerged);

        relatedWordsListWiktionary.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        relatedWordsListWiktionary.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane10.setViewportView(relatedWordsListWiktionary);

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 10)); // NOI18N
        jLabel10.setText("Related Words [Wikipedia]");

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 10)); // NOI18N
        jLabel11.setText("Related Words [Merged]");

        checkBoxIncludeAgrovocdDictionary.setText("Search Agrovoc - Agriculture Dictionary");
        checkBoxIncludeAgrovocdDictionary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxIncludeAgrovocdDictionaryActionPerformed(evt);
            }
        });

        jTextFieldGlossaryFile.setEditable(false);
        jTextFieldGlossaryFile.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldGlossaryFile.setPreferredSize(new java.awt.Dimension(6, 25));
        jTextFieldGlossaryFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGlossaryFileActionPerformed(evt);
            }
        });

        select1.setText("Browse");
        select1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 10)); // NOI18N
        jLabel12.setText("Glossary File");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(departmentName)
                        .addComponent(jScrollPane1)
                        .addComponent(jScrollPane2)
                        .addComponent(tastStatus)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                            .addComponent(selectedGlossaryFilePath)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane9)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(progressBarTextMining, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(searchWord, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(addSource, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(domain, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(select))
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(folderPath, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextFieldGlossaryFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(select1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(224, 224, 224)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxIncludeAgrovocdDictionary)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 30, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(folderPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchWord)
                            .addComponent(reset)
                            .addComponent(addSource)
                            .addComponent(domain)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(jScrollPane6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(departmentName)
                        .addComponent(jLabel9))
                    .addComponent(progressBarTextMining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(selectedGlossaryFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldGlossaryFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(select1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(checkBoxIncludeAgrovocdDictionary))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tastStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tools");

        jMenuItem1.setText("Apply Frequency Threshold");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Form_stage_one.child = null;
        Form_text_mining.selectedGlossaryFilePath.setText("");
        Form_text_mining.meaningArea.setText("");
        if (WordNetSearcher.relatedWordsListModel != null) {
            WordNetSearcher.relatedWordsListModel.removeAllElements();
        }
        StartStemmer.freqmodel.removeAllElements();
        StartStemmer.wordsmodel.removeAllElements();

    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void listofwordsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listofwordsValueChanged
        // TODO add your handling code here:
        new listWordSelection().select();
        freqlist.setSelectedIndex(listofwords.getSelectedIndex());
        freqlist.ensureIndexIsVisible(listofwords.getSelectedIndex());
        //        String s = listofwords.getSelectedValue().toString();
    }//GEN-LAST:event_listofwordsValueChanged

    private void domainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domainActionPerformed
        // TODO add your handling code here:
        new Form_domain_expert();
    }//GEN-LAST:event_domainActionPerformed

    private void addSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSourceActionPerformed


    }//GEN-LAST:event_addSourceActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed

        searchWord.setEnabled(false);
        domain.setEnabled(false);
        addSource.setEnabled(false);
        reset.setEnabled(false);
        selectedGlossaryFilePath.setText("");
        Form_text_mining.meaningArea.setText("");
        WordNetSearcher.relatedWordsListModel.removeAllElements();
        StartStemmer.freqmodel.removeAllElements();
        StartStemmer.wordsmodel.removeAllElements();
        searchWord.setEnabled(false);
        checkstop.setSelected(false);
        checkFreqCount.setSelected(false);
        checkStem.setSelected(false);
    }//GEN-LAST:event_resetActionPerformed

    private void searchWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchWordActionPerformed
        try {
            List list = null;
            words.clear();

            // TODO add your handling code here:
            Form_text_mining.meaningArea.setText("");
            reset.setEnabled(true);
            addSource.setEnabled(true);

            if (Global.glossaryProcessed) {
                domain.setEnabled(true);
            } else {
                domain.setEnabled(false);
            }

            WordNetSearcher.relatedWordsListModel.removeAllElements();
            try {
                new WordNetSearcher().searcher();
            } catch (Exception exception) {
            }

            // create a word net model
            DefaultListModel wordNetModel = new DefaultListModel();

            try {
                for (Object s : WordNetSearcher.getRelatedWordListModelList()) {
                    wordNetModel.addElement(s.toString());
                    words.add(s.toString());
                }

                // assign to word net list
                Form_text_mining.relatedWordsListWordNet.removeAll();
                Form_text_mining.relatedWordsListWordNet.setModel(wordNetModel);
            } catch (Exception exception) {
                Form_text_mining.relatedWordsListWordNet.removeAll();
                Form_text_mining.relatedWordsListWordNet.setModel(wordNetModel);
            }

            // Wiktionary Search
            DefaultListModel wikModel = new DefaultListModel();
            try {
                WiktionarySearcher searcher = new WiktionarySearcher(listWordSelection.selectedWord, "api");
                ArrayList<String> wikList;
                wikList = searcher.getSynonymsAndDerivedWordList();

                // create a wiktionary model                
                for (Object s : wikList) {
                    wikModel.addElement(s.toString());
                    words.add(s.toString());
                }

                // assign to wiktionary list
                Form_text_mining.relatedWordsListWiktionary.removeAll();
                Form_text_mining.relatedWordsListWiktionary.setModel(wikModel);
            } catch (Exception exception) {
                Form_text_mining.relatedWordsListWiktionary.removeAll();
                Form_text_mining.relatedWordsListWiktionary.setModel(wikModel);
            }

            // create a combined model
            DefaultListModel model = new DefaultListModel();
            try {
                for (Object s : words) {
                    model.addElement(s.toString());
                }

                // assign to combined list
                Form_text_mining.relatedWordsListMerged.removeAll();
                Form_text_mining.relatedWordsListMerged.setModel(model);
            } catch (Exception exception) {
                Form_text_mining.relatedWordsListMerged.removeAll();
                Form_text_mining.relatedWordsListMerged.setModel(model);
            }

        } catch (Exception ex) {
            Logger.getLogger(Form_text_mining.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchWordActionPerformed

    private void folderPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folderPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_folderPathActionPerformed

    private void contextstreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_contextstreeValueChanged
        // TODO add your handling code here:
        TreeSelection t = new TreeSelection();
        t.SelectTree();
    }//GEN-LAST:event_contextstreeValueChanged

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        // TODO add your handling code here:        
        new TextMining().execute();
    }//GEN-LAST:event_selectActionPerformed

    private void freqlistValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_freqlistValueChanged
        // TODO add your handling code here:
        listofwords.setSelectedIndex(freqlist.getSelectedIndex());
        listofwords.ensureIndexIsVisible(freqlist.getSelectedIndex());
    }//GEN-LAST:event_freqlistValueChanged

    private void checkBoxIncludeAgrovocdDictionaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxIncludeAgrovocdDictionaryActionPerformed
        // TODO add your handling code here
        includeAgrovocDictionary = checkBoxIncludeAgrovocdDictionary.isSelected();
    }//GEN-LAST:event_checkBoxIncludeAgrovocdDictionaryActionPerformed

    private void jTextFieldGlossaryFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGlossaryFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGlossaryFileActionPerformed

    private void select1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select1ActionPerformed
        final JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        switch (fileChooser.showOpenDialog(this)) {
            case JFileChooser.APPROVE_OPTION: {
                progressBarTextMining.setIndeterminate(true);
                Thread worker = new Thread() {
                    public void run() {
                        File file = fileChooser.getSelectedFile();
                        try {
                            Form_text_mining.progressBarTextMining.setIndeterminate(true);
                            Corpus.fillWordList(file);
                            Form_text_mining.progressBarTextMining.setIndeterminate(false);
                            Form_text_mining.domain.setEnabled(true);
                            Global.glossaryProcessed = true;
                        } catch (IOException ex) {
                            Logger.getLogger(Form_text_mining.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                };
                worker.start();
                break;
            }
            default: {
                break;
            }
        }
    }//GEN-LAST:event_select1ActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton addSource;
    public static javax.swing.JCheckBox checkBoxIncludeAgrovocdDictionary;
    public static javax.swing.JCheckBox checkFreqCount;
    public static javax.swing.JCheckBox checkStem;
    public static javax.swing.JCheckBox checkfile;
    public static javax.swing.JCheckBox checkstop;
    public static javax.swing.JCheckBox checktok;
    public static javax.swing.JCheckBox checktransform;
    public static javax.swing.JCheckBox checkwordselect;
    public static javax.swing.JTree contextstree;
    public static javax.swing.JTextArea departmentField;
    public static javax.swing.JLabel departmentName;
    public static javax.swing.JButton domain;
    public static javax.swing.JFileChooser fileChooser;
    public static javax.swing.JTextField folderPath;
    public static javax.swing.JList freqlist;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    public static javax.swing.JMenu jMenu1;
    public static javax.swing.JMenu jMenu2;
    public static javax.swing.JMenu jMenu3;
    public static javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JScrollPane jScrollPane10;
    public static javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JScrollPane jScrollPane6;
    public static javax.swing.JScrollPane jScrollPane8;
    public static javax.swing.JScrollPane jScrollPane9;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextField jTextFieldGlossaryFile;
    public static javax.swing.JList listofwords;
    public static javax.swing.JTextArea meaningArea;
    public static javax.swing.JProgressBar progressBarTextMining;
    public static javax.swing.JList relatedWordsListMerged;
    public static javax.swing.JList relatedWordsListWiktionary;
    public static javax.swing.JList relatedWordsListWordNet;
    public static javax.swing.JButton reset;
    public static javax.swing.JButton searchWord;
    public static javax.swing.JButton select;
    public static javax.swing.JButton select1;
    public static javax.swing.JTextField selectedGlossaryFilePath;
    public static javax.swing.JLabel tastStatus;
    // End of variables declaration//GEN-END:variables
}
